##Yotube Config

import= [
    # "~/.config/alacritty/themes/catppuccin-mocha.toml"
    # "~/.config/alacritty/themes/nord.toml"
    # "~/.config/alacritty/themes/tokyo-night.toml"
    "~/.config/alacritty/themes/rose-pine.toml"
]

live_config_reload = true


[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium Italic"

[[keyboard.bindings]]
chars = "º"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "¡"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "€"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "¢"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "∞"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "§"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "¶"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "•"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "ª"
key = "Key9"
mods = "Alt"

#[mouse.hints]
#modifiers = "Command"

#[mouse.hints.launcher]
#program = "open"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
dynamic_padding = true
# opacity = 0.5

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 10
y = 10

# [window.position]
# x = 0
# y = 0


[hints]

